server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

spring:
  application:
    name: a-bootiful-registry
